"shape":
  3:
    "bookstore":
      "紀伊國屋書店名古屋空港店": "CD/DVD/BD"
      "TSUTAYA春日井店": "CD/DVD/BD"
      "TSUTAYA春 日 井 店": "CD/DVD/BD"
      "あおい書店西春店": "その他"
      "アマゾン(Kindle)": "Kindle"
      "アマゾン(Kindle unlimited)": "Kindle-U"

