# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
# 参考: https://nekorich.com/cat-names
Abc.create(
  [
    { s: "アーチー", zid: 0 },
    { s: "アーロ", zid: 1 },
    { s: "アイヴァン", zid: 2 },
    { s: "アイリス", zid: 3 },
    { s: "アヴァロン", zid: 4 },
    { s: "アクセル", zid: 5 },
    { s: "あずき", zid: 6 },
    { s: "アディ", zid: 7 },
    { s: "アディソン", zid: 8 },
    { s: "アニー", zid: 9 },
    { s: "アビー", zid: 10 },
    { s: "アポロ", zid: 11 },
    { s: "アリエル", zid: 12 },
    { s: "アリス", zid: 13 },
    { s: "アルド", zid: 14 },
    { s: "アルフィ", zid: 15 },
    { s: "アレックス", zid: 16 },
    { s: "アンバー", zid: 17 },
    { s: "イザベラ", zid: 18 },
    { s: "イジィ", zid: 19 },

  ]
)
Readstatus.create(
  [
    { name: "雑誌-開始" },
    { name: "雑誌-読了" },
    { name: "開始" },
    { name: "読了" },
    { name: "不明" },
    { name: "etc" },
    { name: "" },
  ]
)

Category.create(
  [
    { name: "ソフトウェア" },
    { name: "スキル" },
    { name: "ビジネス" },
    { name: "防衛" },
    { name: "原発" },
    { name: "国際" },
    { name: "社会" },
    { name: "歴史" },
    { name: "天皇" },
    { name: "政治" },
    { name: "思想" },
    { name: "宗教" },
    { name: "中国" },
    { name: "相続" },
    { name: "経済" },
    { name: "法律" },
    { name: "介護" },
    { name: "健康" },
    { name: "工学" },
    { name: "数学" },
    { name: "物理学" },
    { name: "科学" },
    { name: "気候変動" },
    { name: "英語" },
    { name: "語学" },
    { name: "エンタ" },
    { name: "不明" },
    { name: "本以外" },
    { name: "etc" },
    { name: "人文" },
    { name: "言語" },
    { name: "" },
  ]
)

Shape.create(
  [
    { name: "雑誌" },
    { name: "本" },
    { name: "CD/DVD/BD" },
    { name: "Kindle-U" },
    { name: "Kindle" },
    { name: "EBOOK" },
    { name: "その他" },
    { name: "etc" },
    { name: "" },
  ]
)
Bookstore.create(
  [
    { name: "いまじん春日井南店" },
    { name: "TSUTAYA春日井店" },
    { name: "カルコス小牧店" },
    { name: "あおい書店西春店" },
    { name: "ヨシヅヤ師勝店" },
    { name: "復刊ドットコム" },
    { name: "紀伊國屋書店" },
    { name: "紀伊國屋書店ワンダーシティ店" },
    { name: "紀伊國屋書店名古屋空港店" },
    { name: "ジュンク堂書店" },
    { name: "ジュンク堂書店ロフト名古屋店" },
    { name: "ジュンク堂書店名古屋店" },
    { name: "大学堂書店" },
    { name: "脇田書房" },
    { name: "アマゾン" },
    { name: "アマゾン(Kindle unlimited)" },
    { name: "アマゾン(Kindle)" },
    { name: "アマゾンマーケットプレイス" },
    { name: "アマゾン経由" },
    { name: "amazon" },
    { name: "amazon.co.jp" },
    { name: "脇田書店" },
    { name: "BOOK-OFF名古屋味鋺店" },
    { name: "BOOKOFF名古屋味鋺店" },
    { name: "マルツ名古屋小田井店" },

    { name: "あおい書店" },
    { name: "(株)バリューブックス" },
    { name: "Amazon Japan G.K." },
    { name: "BOOK-Stream" },
    { name: "CIAL桜木町店" },
    { name: "もったいない本舗" },
    { name: "エコマケ" },
    { name: "ザ・リブレット" },
    { name: "ザ・リブレットイオンタウン千種店" },
    { name: "セブンイレブン" },
    { name: "フタバ図書" },
    { name: "ブックアイランド三郷倉庫店" },
    { name: "リネットジャパングループ株式会社(ネットオフ)" },
    { name: "三洋堂上前津店" },
    { name: "三洋堂書店上前津店" },
    { name: "三省堂書店名古屋本店" },
    { name: "三省堂書店名古屋高島屋店" },
    { name: "不明" },
    { name: "俸礼謝" },
    { name: "大学書店" },
    { name: "山星書店" },
    { name: "川口書房" },
    { name: "彩流社" },
    { name: "書泉ブックタワー" },
    { name: "有限会社アライド" },
    { name: "服部書店" },
    { name: "株式会社ガジュマル企画" },
    { name: "正文館書店" },
    { name: "正文館書店本店" },
    { name: "正文館本店" },
    { name: "etc" },
    { name: "" },
  ]
)

=begin
=============
["(株)バリューブックス",
 "Amazon Japan G.K.",
 "BOOK-OFF名古屋味鋺店",
 "BOOK-Stream",
 "BOOKOFF名古屋味鋺店",
 "CIAL桜木町店",
 "TSUTAYA春日井店",
 "amazon",
 "amazon.co.jp",
 "あおい書店",
 "あおい書店西春店",
 "いまじん春日井南店",
 "もったいない本舗",
 "アマゾン",
 "アマゾン(Kindle unlimited)",
 "アマゾン(Kindle)",
 "アマゾンマーケットプレイス",
 "アマゾン経由",
 "エコマケ",
 "カルコス小牧店",
 "ザ・リブレット",
 "ザ・リブレットイオンタウン千種店",
 "ジュンク堂書店",
 "ジュンク堂書店ロフト名古屋店",
 "ジュンク堂書店名古屋店",
 "セブンイレブン",
 "フタバ図書",
 "ブックアイランド三郷倉庫店",
 "マルツ名古屋小田井店",
 "ヨシヅヤ師勝店",
 "リネットジャパングループ株式会社(ネットオフ)",
 "三洋堂上前津店",
 "三洋堂書店上前津店",
 "三省堂書店名古屋本店",
 "三省堂書店名古屋高島屋店",
 "不明",
 "俸礼謝",
 "大学堂書店",
 "大学書店",
 "山星書店",
 "川口書房",
 "彩流社",
 "復刊ドットコム",
 "書泉ブックタワー",
 "有限会社アライド",
 "服部書店",
 "株式会社ガジュマル企画",
 "正文館書店",
 "正文館書店本店",
 "正文館本店",
 "紀伊國屋書店",
 "紀伊國屋書店ワンダーシティ店",
 "紀伊國屋書店名古屋空港店",
 "脇田書店",
 "脇田書房"]
=end
